In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
a=pd.read_csv("/content/movies.csv")
a

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
a.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [ ]:
a.tail()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
a.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
a.isna().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
selected_features=[['genres', 'keywords', 'overview', 'tagline',
    'cast', 'crew', 'director',
    'original_language', 'production_companies']]
print(selected_features)

[['genres', 'keywords', 'overview', 'tagline', 'cast', 'crew', 'director', 'original_language', 'production_companies']]

In [ ]:
for features in selected_features:
  a[features]=a[features].fillna('')

In [ ]:
a.isna().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   0
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [ ]:
combined_features=a['genres'] + " "+a['keywords'] + " " +a['overview'] + " " +a['tagline'] + " " +a['cast'] + " " +a['crew'] + " " +a['director'] + " " +a  ['original_language'] + " " +a['production_companies']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [ ]:
Vectorizer=TfidfVectorizer()
feature_Vectors=Vectorizer.fit_transform(combined_features)
print(feature_Vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 996504 stored elements and shape (4803, 244592)>
  Coords	Values
  (0, 186801)	0.004825380491830039
  (0, 186992)	0.005533097640181004
  (0, 203828)	0.006881837446232598
  (0, 232083)	0.006401932703740933
  (0, 204342)	0.006431364212963073
  (0, 198427)	0.011733279136863442
  (0, 196350)	0.01252999988333295
  (0, 205737)	0.008910548165641666
  (0, 234649)	0.019631971541062953
  (0, 242214)	0.0069862992257703855
  (0, 196879)	0.013861331139354179
  (0, 234300)	0.01071817778838601
  (0, 211318)	0.002869104008924103
  (0, 237650)	0.006703076828755089
  (0, 40232)	0.015948431050286253
  (0, 195275)	0.01510010016283622
  (0, 225085)	0.015578854390604137
  (0, 218981)	0.01091137720213165
  (0, 211974)	0.003368149340894707
  (0, 200585)	0.014543380412478648
  (0, 238141)	0.0025065713163557922
  (0, 221623)	0.011201451139193198
  (0, 224952)	0.026703803636129484
  (0, 224115)	0.003967993019166691
  (0, 240539)	0.012456280501546575
  :	:
  (4802, 204487)	0.08595785692114137
  (4802, 205640)	0.0897731221521433
  (4802, 189170)	0.07972462698844705
  (4802, 199259)	0.0897731221521433
  (4802, 231580)	0.08197784312507249
  (4802, 189146)	0.09654773700683128
  (4802, 230787)	0.08103014798925481
  (4802, 200779)	0.061339467875686345
  (4802, 198314)	0.16820864322215842
  (4802, 207448)	0.0897731221521433
  (4802, 194336)	0.09810978610120778
  (4802, 228992)	0.10730236565758813
  (4802, 178671)	0.10730236565758813
  (4802, 180727)	0.11111763088859007
  (4802, 185247)	0.10730236565758813
  (4802, 209632)	0.5824747260698425
  (4802, 166781)	0.11649494521396851
  (4802, 166782)	0.11649494521396851
  (4802, 69937)	0.11649494521396851
  (4802, 183724)	0.11649494521396851
  (4802, 69936)	0.11649494521396851
  (4802, 69938)	0.11649494521396851
  (4802, 186409)	0.11649494521396851
  (4802, 184007)	0.11649494521396851
  (4802, 184008)	0.11649494521396851

In [ ]:
similarity=cosine_similarity(feature_Vectors)
print(similarity)

[[1.         0.57149841 0.82378638 ... 0.32149326 0.07027812 0.15042344]
 [0.57149841 1.         0.5773803  ... 0.2918391  0.06646764 0.13645755]
 [0.82378638 0.5773803  1.         ... 0.33560969 0.07949596 0.15342024]
 ...
 [0.32149326 0.2918391  0.33560969 ... 1.         0.05754167 0.09754641]
 [0.07027812 0.06646764 0.07949596 ... 0.05754167 1.         0.03913374]
 [0.15042344 0.13645755 0.15342024 ... 0.09754641 0.03913374 1.        ]]

In [ ]:
movie_name=input("enter your favourite movie name: ")

enter your favourite movie name: spiderman

In [ ]:
list_of_all_titles=a['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [ ]:
import difflib

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
print(close_match)

Spider-Man

In [ ]:
close_match=find_close_match[0]
print(close_match)

Spider-Man

In [ ]:
index_of_movie=a[a.title==close_match]['index'].values[0]
print(index_of_movie)

159

In [ ]:
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, np.float64(0.7750358605031135)), (1, np.float64(0.5979317493571651)), (2, np.float64(0.7830307511151049)), (3, np.float64(0.8152921766259272)), (4, np.float64(0.7680130412294288)), (5, np.float64(0.698065420169283)), (6, np.float64(0.6451244389367256)), (7, np.float64(0.716009380046413)), (8, np.float64(0.5573654234091814)), (9, np.float64(0.7633750858124586)), (10, np.float64(0.49057843691769315)), (11, np.float64(0.42933778185992216)), (12, np.float64(0.5311742733916058)), (13, np.float64(0.5602051607092136)), (14, np.float64(0.6678475432030593)), (15, np.float64(0.7180369148395971)), (16, np.float64(0.7723334542155061)), (17, np.float64(0.6034460245292395)), (18, np.float64(0.46923816765310045)), (19, np.float64(0.7695106627057448)), (20, np.float64(0.7602213694158527)), (21, np.float64(0.47290596482107)), (22, np.float64(0.7617308107735355)), (23, np.float64(0.5808202399525324)), (24, np.float64(0.6205174286214881)), (25, np.float64(0.6601503656733598)), (26, np.float64(0.7790471214285092)), (27, np.float64(0.7669422330260358)), (28, np.float64(0.8284955996177774)), (29, np.float64(0.5559851710913868)), (30, np.float64(0.8171206921635241)), (31, np.float64(0.5844855308630268)), (32, np.float64(0.48598218046475317)), (33, np.float64(0.6538101012082068)), (34, np.float64(0.4005765479585028)), (35, np.float64(0.6875294211647464)), (36, np.float64(0.7314194183093068)), (37, np.float64(0.5977019358502501)), (38, np.float64(0.7725876640739537)), (39, np.float64(0.5374958180152308)), (40, np.float64(0.6123178248103829)), (41, np.float64(0.6475894401745053)), (42, np.float64(0.6075367564370131)), (43, np.float64(0.6778734014377562)), (44, np.float64(0.7425719918598725)), (45, np.float64(0.5610374696717001)), (46, np.float64(0.7499991148464743)), (47, np.float64(0.7598099309938494)), (48, np.float64(0.6192525741713263)), (49, np.float64(0.4082582187736022)), (50, np.float64(0.6305408647565967)), (51, np.float64(0.4721864842062029)), (52, np.float64(0.5710592708816474)), (53, np.float64(0.39742596413232373)), (54, np.float64(0.3299142633098394)), (55, np.float64(0.5679714214241459)), (56, np.float64(0.761798384924455)), (57, np.float64(0.6668519090272684)), (58, np.float64(0.46533860267591187)), (59, np.float64(0.7481325545622499)), (60, np.float64(0.2974037334012284)), (61, np.float64(0.736726885866279)), (62, np.float64(0.39114693692040114)), (63, np.float64(0.5430774727568564)), (64, np.float64(0.7450718485284028)), (65, np.float64(0.7303974345072562)), (66, np.float64(0.7066918562645097)), (67, np.float64(0.32884513307662755)), (68, np.float64(0.5146280353513675)), (69, np.float64(0.7132223540472964)), (70, np.float64(0.35329182984004265)), (71, np.float64(0.48094979081849065)), (72, np.float64(0.7532229369771156)), (73, np.float64(0.5829940305715601)), (74, np.float64(0.7696031770485766)), (75, np.float64(0.6916991180816189)), (76, np.float64(0.5287490500293038)), (77, np.float64(0.6146280510018048)), (78, np.float64(0.5382649811299774)), (79, np.float64(0.5769607099446206)), (80, np.float64(0.6575381580960937)), (81, np.float64(0.32579865183848833)), (82, np.float64(0.7919718803092506)), (83, np.float64(0.711951748718214)), (84, np.float64(0.7138137466587704)), (85, np.float64(0.6266482718128942)), (86, np.float64(0.20381663618611356)), (87, np.float64(0.7288300754613464)), (88, np.float64(0.608235361008906)), (89, np.float64(0.561527178494548)), (90, np.float64(0.8011721063575276)), (91, np.float64(0.7567041609842061)), (92, np.float64(0.6090908861783005)), (93, np.float64(0.8060290155093195)), (94, np.float64(0.7574812199819636)), (95, np.float64(0.7784474678347232)), (96, np.float64(0.4571486535887184)), (97, np.float64(0.42509767502930185)), (98, np.float64(0.6531391214241454)), (99, np.float64(0.7984570837542249)), (100, np.float64(0.7910830611741893)), (101, np.float64(0.6497882249954569)), (102, np.float64(0.7677163411693303)), (103, np.float64(0.2218453315100983)), (104, np.float64(0.5650657508725436)), (105, np.float64(0.7483667366365834)), (106, np.float64(0.4182965780133893)), (107, np.float64(0.7698649258054495)), (108, np.float64(0.7788109385544543)), (109, np.float64(0.5830432927078064)), (110, np.float64(0.7721478677432838)), (111, np.float64(0.6390462121351687)), (112, np.float64(0.8061502486842526)), (113, np.float64(0.528921404852123)), (114, np.float64(0.5825593492484024)), (115, np.float64(0.5550755814823793)), (116, np.float64(0.4825606941210464)), (117, np.float64(0.7852056382385759)), (118, np.float64(0.6310366690759113)), (119, np.float64(0.8000204642808723)), (120, np.float64(0.23150060965981434)), (121, np.float64(0.44432365348036057)), (122, np.float64(0.34734668871244695)), (123, np.float64(0.5266985019380342)), (124, np.float64(0.4880177201571317)), (125, np.float64(0.4106852180699011)), (126, np.float64(0.6260216840949762)), (127, np.float64(0.715992371871807)), (128, np.float64(0.7745261259070231)), (129, np.float64(0.5677438122119752)), (130, np.float64(0.6521823501400946)), (131, np.float64(0.39830218792414795)), (132, np.float64(0.551592308342979)), (133, np.float64(0.45718697390834623)), (134, np.float64(0.7582086876026466)), (135, np.float64(0.6457835321134516)), (136, np.float64(0.45508293685710455)), (137, np.float64(0.43132602207215603)), (138, np.float64(0.16521981612457154)), (139, np.float64(0.5476285171829669)), (140, np.float64(0.4657999807253012)), (141, np.float64(0.2746663185983956)), (142, np.float64(0.5356458207653351)), (143, np.float64(0.4935759587493049)), (144, np.float64(0.3795504467831652)), (145, np.float64(0.7821479186458999)), (146, np.float64(0.33202492266810046)), (147, np.float64(0.25370552598803126)), (148, np.float64(0.7558366517930426)), (149, np.float64(0.7677661740760604)), (150, np.float64(0.8076723222470985)), (151, np.float64(0.7060671984270439)), (152, np.float64(0.5469786051613019)), (153, np.float64(0.5064755056123603)), (154, np.float64(0.3536409946832306)), (155, np.float64(0.5922081559264437)), (156, np.float64(0.4448506862203001)), (157, np.float64(0.7895128062546365)), (158, np.float64(0.5096421414337774)), (159, np.float64(0.9999999999999993)), (160, np.float64(0.5118316170926426)), (161, np.float64(0.7095636599118849)), (162, np.float64(0.544436239401338)), (163, np.float64(0.5338569476874198)), (164, np.float64(0.7590230914765381)), (165, np.float64(0.811490846525877)), (166, np.float64(0.5660050195297852)), (167, np.float64(0.7702119371022187)), (168, np.float64(0.6089180452347536)), (169, np.float64(0.7847776830380744)), (170, np.float64(0.5410613598516135)), (171, np.float64(0.8137400628892065)), (172, np.float64(0.7636193891276623)), (173, np.float64(0.48087659026315543)), (174, np.float64(0.5390495565948231)), (175, np.float64(0.4110658173093605)), (176, np.float64(0.7679957502000878)), (177, np.float64(0.3543510108268466)), (178, np.float64(0.36191493997108976)), (179, np.float64(0.18439641435562962)), (180, np.float64(0.7927200032110003)), (181, np.float64(0.3622511146268359)), (182, np.float64(0.8019728836735069)), (183, np.float64(0.6500997498569084)), (184, np.float64(0.5458243814872366)), (185, np.float64(0.8164578558524825)), (186, np.float64(0.8115748778268601)), (187, np.float64(0.45482646635970303)), (188, np.float64(0.3578001779246223)), (189, np.float64(0.7197638093961095)), (190, np.float64(0.6224694227255722)), (191, np.float64(0.8026387979772445)), (192, np.float64(0.7118635006956585)), (193, np.float64(0.705112459654243)), (194, np.float64(0.4578628963092795)), (195, np.float64(0.7407218730560241)), (196, np.float64(0.42160431532758647)), (197, np.float64(0.7980105024371243)), (198, np.float64(0.5870725588403035)), (199, np.float64(0.7912739102315595)), (200, np.float64(0.782952651169929)), (201, np.float64(0.7592872532830168)), (202, np.float64(0.46299066268761585)), (203, np.float64(0.550799790693448)), (204, np.float64(0.7800687785179892)), (205, np.float64(0.6144688090411139)), (206, np.float64(0.7726004692275034)), (207, np.float64(0.5079683002719976)), (208, np.float64(0.424822255933626)), (209, np.float64(0.7666168560184365)), (210, np.float64(0.7792165381376335)), (211, np.float64(0.41162852830026475)), (212, np.float64(0.8207475509619122)), (213, np.float64(0.793333192029961)), (214, np.float64(0.40698372436409064)), (215, np.float64(0.5845902677311693)), (216, np.float64(0.5522802081018188)), (217, np.float64(0.688280491081627)), (218, np.float64(0.7609156316069154)), (219, np.float64(0.4010518165281933)), (220, np.float64(0.7411190958945348)), (221, np.float64(0.32668030893549826)), (222, np.float64(0.762132095968512)), (223, np.float64(0.8024634621216786)), (224, np.float64(0.4921580805047992)), (225, np.float64(0.4805723377306705)), (226, np.float64(0.4809644178521107)), (227, np.float64(0.7773978212876713)), (228, np.float64(0.534528712548222)), (229, np.float64(0.3513831164371599)), (230, np.float64(0.41766628438976605)), (231, np.float64(0.7482094655470325)), (232, np.float64(0.7417894925226446)), (233, np.float64(0.4195295899417011)), (234, np.float64(0.39114091904481146)), (235, np.float64(0.4320484918416951)), (236, np.float64(0.5867579250291733)), (237, np.float64(0.2513300985748902)), (238, np.float64(0.5690319418688934)), (239, np.float64(0.6598536701711211)), (240, np.float64(0.7757784771725363)), (241, np.float64(0.3825820129843877)), (242, np.float64(0.7813239793396825)), (243, np.float64(0.4658569571434614)), (244, np.float64(0.7389913792461453)), (245, np.float64(0.48427935777169595)), (246, np.float64(0.7949519555173872)), (247, np.float64(0.7759622774941805)), (248, np.float64(0.4679038911456549)), (249, np.float64(0.7208783964472304)), (250, np.float64(0.8028747892490427)), (251, np.float64(0.5445418488026426)), (252, np.float64(0.39205286328751776)), (253, np.float64(0.7321212734059039)), (254, np.float64(0.49570196766836133)), (255, np.float64(0.6077358594487741)), (256, np.float64(0.7271895655361738)), (257, np.float64(0.6424032795655449)), (258, np.float64(0.2933091873168668)), (259, np.float64(0.7704813110351885)), (260, np.float64(0.76879241864213)), (261, np.float64(0.7729369469411775)), (262, np.float64(0.5511198941801844)), (263, np.float64(0.7892866579212875)), (264, np.float64(0.5577480772803267)), (265, np.float64(0.43582631992625903)), (266, np.float64(0.80115665667264)), (267, np.float64(0.7758997221578939)), (268, np.float64(0.3159007423455648)), (269, np.float64(0.6532320713468697)), (270, np.float64(0.7430677988188521)), (271, np.float64(0.6763582404977303)), (272, np.float64(0.139268426533428)), (273, np.float64(0.5616995801310352)), (274, np.float64(0.7403463949598227)), (275, np.float64(0.8105894632917329)), (276, np.float64(0.8022369212602362)), (277, np.float64(0.779920502254436)), (278, np.float64(0.47819346784898203)), (279, np.float64(0.701461645713666)), (280, np.float64(0.7564088039763223)), (281, np.float64(0.6928866233066603)), (282, np.float64(0.5362018925859537)), (283, np.float64(0.4858856594423955)), (284, np.float64(0.3082102626234473)), (285, np.float64(0.2547309757989998)), (286, np.float64(0.7249545336744887)), (287, np.float64(0.7444009216337574)), (288, np.float64(0.576047289664031)), (289, np.float64(0.4835024084756587)), (290, np.float64(0.7580269709093993)), (291, np.float64(0.7879507056114178)), (292, np.float64(0.5578682241023013)), (293, np.float64(0.30106240069504575)), (294, np.float64(0.5136768314345884)), (295, np.float64(0.5272186644204341)), (296, np.float64(0.8018569546743786)), (297, np.float64(0.7419275706842641)), (298, np.float64(0.8117842896405413)), (299, np.float64(0.4224917800665937)), (300, np.float64(0.6295113302922587)), (301, np.float64(0.7738904895767401)), (302, np.float64(0.37794979989062644)), (303, np.float64(0.812091339482068)), (304, np.float64(0.6986309020340711)), (305, np.float64(0.5838932947323648)), (306, np.float64(0.4863035918215647)), (307, np.float64(0.7099332144055773)), (308, np.float64(0.7534242048709049)), (309, np.float64(0.3965214443929147)), (310, np.float64(0.7384176281994163)), (311, np.float64(0.30791027017259304)), (312, np.float64(0.7273192217341484)), (313, np.float64(0.3744406087274694)), (314, np.float64(0.48101016163059074)), (315, np.float64(0.3161124236289241)), (316, np.float64(0.5754625536041501)), (317, np.float64(0.5990885100847548)), (318, np.float64(0.3955499640142211)), (319, np.float64(0.47694278050463973)), (320, np.float64(0.7989194276316788)), (321, np.float64(0.3682701903402007)), (322, np.float64(0.787353779372906)), (323, np.float64(0.3972981077904934)), (324, np.float64(0.5640356492393385)), (325, np.float64(0.35243435700706194)), (326, np.float64(0.7084869277416496)), (327, np.float64(0.5282808482880801)), (328, np.float64(0.7252477970943687)), (329, np.float64(0.5614930181816)), (330, np.float64(0.5989712226289337)), (331, np.float64(0.6532570840011785)), (332, np.float64(0.6258590770384328)), (333, np.float64(0.7119612171399697)), (334, np.float64(0.7776502551319726)), (335, np.float64(0.7577006234957189)), (336, np.float64(0.7572840859632519)), (337, np.float64(0.7540890463786923)), (338, np.float64(0.8025008938101914)), (339, np.float64(0.7324430999289783)), (340, np.float64(0.39281589482300894)), (341, np.float64(0.6571693050491245)), (342, np.float64(0.7871405538911503)), (343, np.float64(0.6950123153712511)), (344, np.float64(0.5376021083504272)), (345, np.float64(0.2940394812407587)), (346, np.float64(0.7841883934967954)), (347, np.float64(0.47284211218168587)), (348, np.float64(0.284942132991854)), (349, np.float64(0.5156286288881863)), (350, np.float64(0.6139323959355389)), (351, np.float64(0.7228641319003617)), (352, np.float64(0.5278160951534723)), (353, np.float64(0.5446816294656467)), (354, np.float64(0.7877852735873919)), (355, np.float64(0.6597273185867125)), (356, np.float64(0.5245813209288909)), (357, np.float64(0.3139414543344118)), (358, np.float64(0.7000846902164489)), (359, np.float64(0.3567640511849238)), (360, np.float64(0.5246135165639638)), (361, np.float64(0.5897096706465846)), (362, np.float64(0.5816302801849731)), (363, np.float64(0.8031647130063009)), (364, np.float64(0.3487234512263378)), (365, np.float64(0.8150821547497604)), (366, np.float64(0.3659586514224506)), (367, np.float64(0.7759807342407915)), (368, np.float64(0.5729086181183588)), (369, np.float64(0.3568529644879261)), (370, np.float64(0.7109639897727724)), (371, np.float64(0.4138789555287058)), (372, np.float64(0.5872682321301687)), (373, np.float64(0.6175139737417888)), (374, np.float64(0.3587494056027557)), (375, np.float64(0.3235080901595539)), (376, np.float64(0.2930935155787151)), (377, np.float64(0.41358474802765327)), (378, np.float64(0.41481941320932414)), (379, np.float64(0.6763678696234791)), (380, np.float64(0.6677427637078971)), (381, np.float64(0.16120706812710814)), (382, np.float64(0.7070332636634198)), (383, np.float64(0.7595632680711594)), (384, np.float64(0.3897970177479784)), (385, np.float64(0.6720373856658848)), (386, np.float64(0.8028036195012325)), (387, np.float64(0.7703549252774022)), (388, np.float64(0.7893540606457812)), (389, np.float64(0.5520593738441645)), (390, np.float64(0.37713834667938245)), (391, np.float64(0.48378811139872346)), (392, np.float64(0.4889995852805913)), (393, np.float64(0.33467110934763017)), (394, np.float64(0.4744544055550015)), (395, np.float64(0.3258074389382202)), (396, np.float64(0.48995072487500335)), (397, np.float64(0.37885725620217076)), (398, np.float64(0.6262104193663105)), (399, np.float64(0.3804079087631192)), (400, np.float64(0.7507780348530205)), (401, np.float64(0.7136335483395088)), (402, np.float64(0.5774689070522597)), (403, np.float64(0.771865539492594)), (404, np.float64(0.4338171071022811)), (405, np.float64(0.6850960415727931)), (406, np.float64(0.5395027485137128)), (407, np.float64(0.7085722508361838)), (408, np.float64(0.8003042378615165)), (409, np.float64(0.3447104590373025)), (410, np.float64(0.5591008188463055)), (411, np.float64(0.22309093750679282)), (412, np.float64(0.821171470861197)), (413, np.float64(0.3929685050965063)), (414, np.float64(0.7827003341001596)), (415, np.float64(0.7215961972786844)), (416, np.float64(0.4127089574908384)), (417, np.float64(0.421980499937423)), (418, np.float64(0.34818455172253837)), (419, np.float64(0.7348558571265944)), (420, np.float64(0.3781305907956732)), (421, np.float64(0.6274774142773221)), (422, np.float64(0.6988259518501762)), (423, np.float64(0.779218809946524)), (424, np.float64(0.7648065373376949)), (425, np.float64(0.76359995427459)), (426, np.float64(0.6761723882569285)), (427, np.float64(0.19711765375242954)), (428, np.float64(0.3860754426319001)), (429, np.float64(0.37078372120449266)), (430, np.float64(0.545686123588687)), (431, np.float64(0.5441062602996198)), (432, np.float64(0.7822235483999808)), (433, np.float64(0.41818983493422984)), (434, np.float64(0.448924992185394)), (435, np.float64(0.3841134959551213)), (436, np.float64(0.411739814547601)), (437, np.float64(0.4094252687130325)), (438, np.float64(0.2532619307940451)), (439, np.float64(0.5714292290697587)), (440, np.float64(0.46305194978253733)), (441, np.float64(0.6740906253126983)), (442, np.float64(0.6501897571782492)), (443, np.float64(0.17323461334890497)), (444, np.float64(0.7796571549358967)), (445, np.float64(0.6482169488230762)), (446, np.float64(0.5990602978765354)), (447, np.float64(0.7752355329599288)), (448, np.float64(0.7365140064835053)), (449, np.float64(0.7475022378421939)), (450, np.float64(0.3450267168704631)), (451, np.float64(0.7860949045148051)), (452, np.float64(0.774199804375446)), (453, np.float64(0.5035707411783307)), (454, np.float64(0.7245539935986968)), (455, np.float64(0.439018414960412)), (456, np.float64(0.7492434003434396)), (457, np.float64(0.5917217817837066)), (458, np.float64(0.2590197410736533)), (459, np.float64(0.5005183550964449)), (460, np.float64(0.2898728502549816)), (461, np.float64(0.7717322183651916)), (462, np.float64(0.7589997767154211)), (463, np.float64(0.1458353359196518)), (464, np.float64(0.2941998077709475)), (465, np.float64(0.612967441941015)), (466, np.float64(0.5010085463320927)), (467, np.float64(0.46865968118795776)), (468, np.float64(0.3214491774203444)), (469, np.float64(0.44657620795230807)), (470, np.float64(0.40455327046042133)), (471, np.float64(0.2890909874437084)), (472, np.float64(0.7651318651351915)), (473, np.float64(0.504333857082576)), (474, np.float64(0.4110281717132783)), (475, np.float64(0.24212510007950822)), (476, np.float64(0.5683239155524908)), (477, np.float64(0.5968424005737442)), (478, np.float64(0.7413206615373542)), (479, np.float64(0.3201912601952046)), (480, np.float64(0.35757323217561604)), (481, np.float64(0.6802869204844428)), (482, np.float64(0.18313026569222277)), (483, np.float64(0.7794168069223535)), (484, np.float64(0.3685330938432258)), (485, np.float64(0.3587577621647024)), (486, np.float64(0.7136586970632597)), (487, np.float64(0.7609206243122527)), (488, np.float64(0.4393896308089133)), (489, np.float64(0.45884014424729624)), (490, np.float64(0.5507353119487959)), (491, np.float64(0.6272865575352227)), (492, np.float64(0.1651166535870202)), (493, np.float64(0.6838118862458503)), (494, np.float64(0.5777914336604688)), (495, np.float64(0.7265974553052074)), (496, np.float64(0.5198310023779562)), (497, np.float64(0.3179977061905375)), (498, np.float64(0.7868217035806157)), (499, np.float64(0.3851992145130662)), (500, np.float64(0.7735916270830873)), (501, np.float64(0.2562730403405426)), (502, np.float64(0.46476260592031354)), (503, np.float64(0.2975479411111919)), (504, np.float64(0.6282711250563531)), (505, np.float64(0.808041182517937)), (506, np.float64(0.5692111181888837)), (507, np.float64(0.6938334459988618)), (508, np.float64(0.7706917249747816)), (509, np.float64(0.6597687519651241)), (510, np.float64(0.7566685836074728)), (511, np.float64(0.5321245091098548)), (512, np.float64(0.5421480986786795)), (513, np.float64(0.5434571496290752)), (514, np.float64(0.3084298354675058)), (515

In [ ]:
sorted_similar_movies=sorted(similarity_score,key=lambda i:i[1], reverse=True)
print(sorted_similar_movies)

[(159, np.float64(0.9999999999999993)), (28, np.float64(0.8284955996177774)), (412, np.float64(0.821171470861197)), (212, np.float64(0.8207475509619122)), (30, np.float64(0.8171206921635241)), (185, np.float64(0.8164578558524825)), (3, np.float64(0.8152921766259272)), (365, np.float64(0.8150821547497604)), (171, np.float64(0.8137400628892065)), (1430, np.float64(0.8131944386366732)), (303, np.float64(0.812091339482068)), (298, np.float64(0.8117842896405413)), (186, np.float64(0.8115748778268601)), (165, np.float64(0.811490846525877)), (275, np.float64(0.8105894632917329)), (654, np.float64(0.8081683004177918)), (505, np.float64(0.808041182517937)), (150, np.float64(0.8076723222470985)), (112, np.float64(0.8061502486842526)), (93, np.float64(0.8060290155093195)), (1823, np.float64(0.8057782138638039)), (529, np.float64(0.8044690895421597)), (1133, np.float64(0.8039461255375097)), (583, np.float64(0.8039413308795215)), (568, np.float64(0.803866028219206)), (828, np.float64(0.8035332100420478)), (864, np.float64(0.8033099055621556)), (363, np.float64(0.8031647130063009)), (250, np.float64(0.8028747892490427)), (386, np.float64(0.8028036195012325)), (191, np.float64(0.8026387979772445)), (338, np.float64(0.8025008938101914)), (223, np.float64(0.8024634621216786)), (276, np.float64(0.8022369212602362)), (182, np.float64(0.8019728836735069)), (714, np.float64(0.8018989376097432)), (296, np.float64(0.8018569546743786)), (90, np.float64(0.8011721063575276)), (266, np.float64(0.80115665667264)), (1056, np.float64(0.8009199105321045)), (408, np.float64(0.8003042378615165)), (119, np.float64(0.8000204642808723)), (320, np.float64(0.7989194276316788)), (99, np.float64(0.7984570837542249)), (197, np.float64(0.7980105024371243)), (718, np.float64(0.7975827781459642)), (673, np.float64(0.7967267769530162)), (246, np.float64(0.7949519555173872)), (213, np.float64(0.793333192029961)), (694, np.float64(0.7931111424441016)), (767, np.float64(0.7928664951112927)), (180, np.float64(0.7927200032110003)), (82, np.float64(0.7919718803092506)), (199, np.float64(0.7912739102315595)), (579, np.float64(0.7911088554840532)), (100, np.float64(0.7910830611741893)), (1821, np.float64(0.7896283279958951)), (157, np.float64(0.7895128062546365)), (388, np.float64(0.7893540606457812)), (263, np.float64(0.7892866579212875)), (544, np.float64(0.7888572024409876)), (1042, np.float64(0.7884352769549209)), (291, np.float64(0.7879507056114178)), (724, np.float64(0.7878234539013715)), (354, np.float64(0.7877852735873919)), (322, np.float64(0.787353779372906)), (342, np.float64(0.7871405538911503)), (498, np.float64(0.7868217035806157)), (451, np.float64(0.7860949045148051)), (668, np.float64(0.7857188329344926)), (117, np.float64(0.7852056382385759)), (702, np.float64(0.7851322803477615)), (169, np.float64(0.7847776830380744)), (346, np.float64(0.7841883934967954)), (562, np.float64(0.7840890674144924)), (1707, np.float64(0.7838908587217542)), (830, np.float64(0.7837509949005248)), (577, np.float64(0.7835223705813007)), (2, np.float64(0.7830307511151049)), (746, np.float64(0.7830053258344435)), (200, np.float64(0.782952651169929)), (414, np.float64(0.7827003341001596)), (432, np.float64(0.7822235483999808)), (145, np.float64(0.7821479186458999)), (2735, np.float64(0.7819223947338992)), (242, np.float64(0.7813239793396825)), (2743, np.float64(0.7804618671065715)), (2283, np.float64(0.7804149959228814)), (924, np.float64(0.7803892293230283)), (204, np.float64(0.7800687785179892)), (1009, np.float64(0.7799827570957927)), (277, np.float64(0.779920502254436)), (444, np.float64(0.7796571549358967)), (483, np.float64(0.7794168069223535)), (423, np.float64(0.779218809946524)), (210, np.float64(0.7792165381376335)), (26, np.float64(0.7790471214285092)), (108, np.float64(0.7788109385544543)), (3342, np.float64(0.7787545989731136)), (1773, np.float64(0.7786475300580575)), (95, np.float64(0.7784474678347232)), (662, np.float64(0.7782925694579342)), (635, np.float64(0.7782717082244727)), (2516, np.float64(0.7780036922200895)), (334, np.float64(0.7776502551319726)), (935, np.float64(0.7775265588260964)), (227, np.float64(0.7773978212876713)), (2039, np.float64(0.776312938774675)), (367, np.float64(0.7759807342407915)), (247, np.float64(0.7759622774941805)), (267, np.float64(0.7758997221578939)), (240, np.float64(0.7757784771725363)), (447, np.float64(0.7752355329599288)), (515, np.float64(0.7751033094584094)), (0, np.float64(0.7750358605031135)), (1422, np.float64(0.7746285140355275)), (128, np.float64(0.7745261259070231)), (452, np.float64(0.774199804375446)), (587, np.float64(0.7741754297744277)), (301, np.float64(0.7738904895767401)), (625, np.float64(0.7738841185372446)), (500, np.float64(0.7735916270830873)), (675, np.float64(0.7733312297261147)), (261, np.float64(0.7729369469411775)), (936, np.float64(0.7728228089509271)), (206, np.float64(0.7726004692275034)), (38, np.float64(0.7725876640739537)), (817, np.float64(0.7724431619786445)), (16, np.float64(0.7723334542155061)), (628, np.float64(0.7721773467013511)), (716, np.float64(0.7721590198244528)), (110, np.float64(0.7721478677432838)), (611, np.float64(0.7720810127511922)), (403, np.float64(0.771865539492594)), (574, np.float64(0.7717559854474175)), (461, np.float64(0.7717322183651916)), (508, np.float64(0.7706917249747816)), (1486, np.float64(0.7706479735846331)), (728, np.float64(0.7705434649091679)), (259, np.float64(0.7704813110351885)), (387, np.float64(0.7703549252774022)), (167, np.float64(0.7702119371022187)), (1249, np.float64(0.770191948555428)), (958, np.float64(0.7700279178111613)), (532, np.float64(0.769887401021931)), (107, np.float64(0.7698649258054495)), (1210, np.float64(0.7697407278533986)), (1634, np.float64(0.7696557393965668)), (74, np.float64(0.7696031770485766)), (1054, np.float64(0.769545991403762)), (19, np.float64(0.7695106627057448)), (2143, np.float64(0.7694925419526392)), (589, np.float64(0.7690438928417701)), (260, np.float64(0.76879241864213)), (534, np.float64(0.7687320764779523)), (1548, np.float64(0.7683501440977195)), (1338, np.float64(0.7682472203928993)), (726, np.float64(0.7682092338355857)), (1540, np.float64(0.7681342028943543)), (1896, np.float64(0.7680979449851727)), (4, np.float64(0.7680130412294288)), (176, np.float64(0.7679957502000878)), (149, np.float64(0.7677661740760604)), (102, np.float64(0.7677163411693303)), (2459, np.float64(0.7675020401323088)), (27, np.float64(0.7669422330260358)), (1239, np.float64(0.7668328072920523)), (2286, np.float64(0.766778064345059)), (209, np.float64(0.7666168560184365)), (732, np.float64(0.7665966152304975)), (1205, np.float64(0.7665178335924263)), (1906, np.float64(0.7661191312395611)), (3031, np.float64(0.7652268380182312)), (472, np.float64(0.7651318651351915)), (688, np.float64(0.7649279896352915)), (424, np.float64(0.7648065373376949)), (762, np.float64(0.764230306407642)), (1407, np.float64(0.7640504874771898)), (172, np.float64(0.7636193891276623)), (425, np.float64(0.76359995427459)), (9, np.float64(0.7633750858124586)), (1637, np.float64(0.7632835018402309)), (909, np.float64(0.7632720368096523)), (1866, np.float64(0.7626856265401835)), (222, np.float64(0.762132095968512)), (809, np.float64(0.7619999415894468)), (1161, np.float64(0.7619885972498244)), (56, np.float64(0.761798384924455)), (22, np.float64(0.7617308107735355)), (883, np.float64(0.7616987067103914)), (829, np.float64(0.7609317440078781)), (487, np.float64(0.7609206243122527)), (218, np.float64(0.7609156316069154)), (1374, np.float64(0.7607663026522444)), (1810, np.float64(0.7607544344579097)), (630, np.float64(0.7605311704078832)), (20, np.float64(0.7602213694158527)), (2310, np.float64(0.7599702830750417)), (47, np.float64(0.7598099309938494)), (383, np.float64(0.7595632680711594)), (201, np.float64(0.7592872532830168)), (956, np.float64(0.7592268221934653)), (164, np.float64(0.7590230914765381)), (462, np.float64(0.7589997767154211)), (895, np.float64(0.7588226785645702)), (1831, np.float64(0.7583736306355956)), (134, np.float64(0.7582086876026466)), (290, np.float64(0.7580269709093993)), (564, np.float64(0.7579597712017243)), (2217, np.float64(0.7578563883188685)), (335, np.float64(0.7577006234957189)), (94, np.float64(0.7574812199819636)), (932, np.float64(0.7573358178889017)), (2023, np.float64(0.7573324126171016)), (336, np.float64(0.7572840859632519)), (607, np.float64(0.7572625506600686)), (91, np.float64(0.7567041609842061)), (510, np.float64(0.7566685836074728)), (280, np.float64(0.7564088039763223)), (148, np.float64(0.7558366517930426)), (2730, np.float64(0.7550710967347612)), (731, np.float64(0.7545411424804492)), (1577, np.float64(0.754507089721528)), (1059, np.float64(0.7544828880024467)), (337, np.float64(0.7540890463786923)), (740, np.float64(0.7538410620646226)), (590, np.float64(0.7536633331799094)), (308, np.float64(0.7534242048709049)), (1145, np.float64(0.7532718748302086)), (582, np.float64(0.7532667055396866)), (72, np.float64(0.7532229369771156)), (1826, np.float64(0.7513026458843098)), (609, np.float64(0.7510466135922116)), (3009, np.float64(0.7509592193820411)), (400, np.float64(0.7507780348530205)), (1516, np.float64(0.750072577814773)), (46, np.float64(0.7499991148464743)), (1019, np.float64(0.7499525561953736)), (759, np.float64(0.7495716402788956)), (2123, np.float64(0.7495379913693353)), (1995, np.float64(0.7492603602954999)), (456, np.float64(0.7492434003434396)), (1141, np.float64(0.7486739617601568)), (2029, np.float64(0.7486437223695837)), (632, np.float64(0.7485823924110886)), (1789, np.float64(0.7485562694385471)), (105, np.float64(0.7483667366365834)), (621, np.float64(0.7483165028650177)), (994, np.float64(0.7482306093384534)), (231, np.float64(0.7482094655470325)), (59, np.float64(0.7481325545622499)), (1535, np.float64(0.7480134878764063)), (1716, np.float64(0.747894423862541)), (531, np.float64(0.7476474469188009)), (449, np.float64(0.7475022378421939)), (1641, np.float64(0.7474792356828694)), (3057, np.float64(0.747246868723703)), (818, np.float64(0.7470333242119439)), (957, np.float64(0.7470080344154814)), (1839, np.float64(0.7463014484268609)), (603, np.float64(0.7461095598958322)), (1553, np.float64(0.7460065723626833)), (955, np.float64(0.7459609694159045)), (64, np.float64(0.7450718485284028)), (2607, np.float64(0.7450459458389618)), (787, np.float64(0.7445194591638672)), (287, np.float64(0.7444009216337574)), (1143, np.float64(0.7442841502964318)), (642, np.float64(0.7434432170857282)), (693, np.float64(0.7432601193963446)), (270, np.float64(0.7430677988188521)), (2983, np.float64(0.7430432695299422)), (3311, np.float64(0.7428458647233749)), (44, np.float64(0.7425719918598725)), (738, np.float64(0.7425137612673447)), (1450, np.float64(0.7424124476301992)), (2810, np.float64(0.742328277966981)), (2425, np.float64(0.7420298063638334)), (297, np.float64(0.7419275706842641)), (2517, np.float64(0.7418621550513639)), (232, np.float64(0.7417894925226446)), (1177, np.float64(0.7414617681073701)), (478, np.float64(0.7413206615373542)), (811, np.float64(0.7413057958284233)), (220, np.float64(0.7411190958945348)), (1465, np.float64(0.7408888829845391)), (195, np.float64(0.7407218730560241)), (1020, np.float64(0.7404791098232734)), (274, np.float64(0.7403463949598227)), (708, np.float64(0.7401251736408396)), (2016, np.float64(0.7400336540814909)), (1037, np.float64(0.7397805576630235)), (2018, np.float64(0.7395190888024308)), (866, np.float64(0.7393042807316321)), (987, np.float64(0.7390308357554473)), (244, np.float64(0.7389913792461453)), (1093, np.float64(0.7388011678082078)), (1122, np.float64(0.7385632423650863)), (310, np.float64(0.7384176281994163)), (1395, np.float64(0.7381387694485815)), (1968, np.float64(0.7380964825184085)), (1881, np.float64(0.738068322014314)), (2200, np.float64(0.7368634554715522)), (61, np.float64(0.736726885866279)), (3360, np.float64(0.7367096328681323)), (1491, np.float64(0.7365514803527414)), (1203, np.float64(0.736537178597018)), (448, np.float64(0.7365140064835053)), (2091, np.float64(0.7362118206787645)), (1389, np.float64(0.7360667921976011)), (2282, np.float64(0.7360641991471697)), (1964, np.float64(0.7356872107723467)), (622, np.float64(0.734905357767699)), (419, np.float64(0.7348558571265944)), (788, np.float64(0.7341235672342467)), (1187, np.float64(0.733727931851868)), (666, np.float64(0.7329751849773611)), (2926, np.float64(0.7329538220367328)), (2990, np.float64(0.7329260594580658)), (773, np.float64(0.7328904126503055)), (1449, np.float64(0.7324629072263319)), (339, np.float64(0.7324430999289783)), (253, np.float64(0.7321212734059039)), (941, np.float64(0.7317145315092167)), (1245, np.float64(0.7315957368782842)), (36, np.float64(0.7314194183093068)), (747, np.float64(0.7313791453546276)), (1702, np.float64(0.7313096708132245)), (1704, np.float64(0.7312673938030223)), (671, np.float64(0.7304025863712037)), (65, np.float64(0.7303974345072562)), (548, np.float64(0.7299277782523161)), (877, np.float64(0.7296508330374258)), (684, np.float64(0.7295239773007918)), (1605, np.float64(0.7292845965012819)), (2293, np.float64(0.7290452033297243)), (87, np.float64(0.7288300754613464)), (951, np.float64(0.728386320484758)), (689, np.float64(0.7283168211245609)), (758, np.float64(0.7281637392843859)), (1647, np.float64(0.7281367355273376)), (1002, np.float64(0.7274711021914594)), (2308, np.float64(0.7273423061758536)), (312, np.float64(0.7273192217341484)), (256, np.float64(0.7271895655361738)), (1557, np.float64(0.727141867277534)), (1468, np.float64(0.7266500108343444)), (495, np.float64(0.7265974553052074)), (2558, np.float64(0.7264566327232839)), (526, np.float64(0.7263193289485028)), (739, np.float64(0.7262894474185562)), (822, np.float64(0.7258233452804)), (2405, np.float64(0.7255199128925129)), (328, np.float64(0.7252477970943687)), (853, np.float64(0.7250123976306507)), (286, np.float64(0.7249545336744887)), (2525, np.float64(0.7248020172460751)), (454, np.float64(0.7245539935986968)), (1598, np.float64(0.7238447275294037)), (3234, np.float64(0.7236745458633439)), (919, np.float64(0.7233580385749525)), (1220, np.float64(0.7233422990818715)), (1348, np.float64(0.7231331798907487)), (351, np.float64(0.7228641319003617)), (2253, np.float64(0.7228541804661228)), (3235, np.float64(0.7227865187147833)), (1412, np.float64(0.7222681321888744)), (1835, np.float64(0.7222269655949667)), (1547, np.float64(0.7218898833310697)), (1993, np.float64(0.7216567899157992)), (3766, np.float64(0.7216116754633543)), (415, np.float64(0.7215961972786844)), (899, np.float64(0.7214127656082568)), (2547, np.float64(0.7213441745342456)), (573, np.float64(0.7210804080840815)), (249, np.float64(0.7208783964472304)), (1627, np.float64(0.7207639919310286)), (2853, np.float64(0.7204735788244268)), (189, np.float64(0.7197638093961095)), (1915, np.float64(0.7195267285590411)), (2454, np.float64(0.7193328550328093)), (1872, np.float64(0.7191182028123988)), (1926, np.float64(0.7190213861826611)), (2240, np.float64(0.7188884926185636)), (771, np.float64(0.7187144377748139)), (2105, np.float64(0.7186902514390794)), (1048, np.float64(0.718658403426972)), (790, np.float64(0.7184619992714413)), (1893, np.float64(0.7182626947719528)), (2274, np.float64(0.718079888428062)), (1179, np.float64(0.7180777025711884)), (15, np.float64(0.7180369148395971)), (1554, np.float64(0.7170671705554901)), (1111, np.float64(0.7167774921472816)), (821, np.float64(0.7161601262261772)), (7, np.float64(0.716009380046413)), (127, np.float64(0.715992371871807)), (525, np.float64(0.7155836883069309)), (556, np.float64(0.7150095690276936)), (1613, np.float64(0.7141487591191423)), (687, np.float64(0.7140879816846472)), (84, np.float64(0.7138137466587704)), (1181, np.float64(0.7137935690908704)), (2849, np.float64(0.7136983781732286)), (486, np.float64(0.7136586970632597)), (401, np.float64(0.7136335483395088)), (69, np.float64(0.7132223540472964)), (3742, np.float64(0.712850011672592)), (595, np.float64(0.7127946497743849)), (2720, np.float64(0.712705796739584)), (1479, np.float64(0.7126454435226866)), (2935, np.float64(0.7122233631924617)), (333, np.float64(0.7119612171399697)), (83, np.float64(0.711951748718214)), (192, np.float64(0.7118635006956585)), (1199, np.float64(0.7118629848402269)), (1379, np.float64(0.7116056240559987)), (3053, np.float64(0.7114238565745916)), (370, np.float64(0.7109639897727724)), (2428, np.float64(0.710910879042982)), (1010, np.float64(0.7108461816404849)), (3334, np.float64(0.7108385256125203)), (772, np.float64(0.7106080074739726)), (800, np.float64(0.7105839965192885)), (1326, np.float64(0.7105526938178419)), (3365, np.float64(0.7103963720882334)), (855, np.float64(0.7103711106463839)), (307, np.float64(0.7099332144055773)), (2278, np.float64(0.7095880384560781)), (161, np.float64(0.7095636599118849)), (2072, np.float64(0.7095294343121958)), (888, np.float64(0.7093158671543208)), (1986, np.float64(0.709300688316531)), (1633, np.float64(0.7090175157427825)), (2035, np.float64(0.7089259319468167)), (1684, np.float64(0.7088072931521355)), (407, np.float64(0.7085722508361838)), (326, np.float64(0.7084869277416496)), (2716, np.float64(0.7082455045182756)), (1552, np.float64(0.708156268649272)), (2348, np.float64(0.7076224653394076)), (2406, np.float64(0.707443672803829)), (565, np.float64(0.7073054224336918)), (2934, np.float64(0.7070884873850733)), (382, np.float64(0.7070332636634198)), (3015, np.float64(0.706908539387206)), (66, np.float64(0.7066918562645097)), (591, np.float64(0.7064416477422094)), (151, np.float64(0.7060671984270439)), (1424, np.float64(0.7059100808757431)), (2218, np.float64(0.7054168027798647)), (4291, np.float64(0.7053641092864908)), (193, np.float64(0.705112459654243)), (2185, np.float64(0.7047082632755659)), (1794, np.float64(0.7044002032587569)), (1796, np.float64(0.7043838717670868)), (555, np.float64(0.704158030223055)), (792, np.float64(0.7032477412498459)), (521, np.float64(0.7032361220987254)), (2318, np.float64(0.7031958195819292)), (1645, np.float64(0.7026754799936221)), (900, np.float64(0.7026465165413421)), (1530, np.float64(0.7023317536360075)), (2297, np.float64(0.7021627840689424)), (917, np.float64(0.7016986746409654)), (1000, np.float64(0.7016684910698688)), (634, np.float64(0.701653034387747)), (279, np.float64(0.701461645713666)), (1723, np.float64(0.7012355007813247)), (2212, np.float64(0.7011592109875439)), (2834, np.float64(0.7008840876476226)), (840, np.float64(0.7008705955511307)), (1423, np.float64(0.7008640928363342)), (3238, np.float64(0.7004922829339049)), (2824, np.float64(0.7002572682408706)), (358, np.float64(0.7000846902164489)), (1153, np.float64(0.6999714698739407)), (3604, np.float64(0.6998076911906786)), (1809, np.float64(0.6996120365725425)), (2552, np.float64(0.6994572996352431)), (549, np.float64(0.6993908328442345)), (1201, np.float64(0.6992256204538899)), (3169, np.float64(0.6989487163825314)), (422, np.float64(0.6988259518501762)), (3865, np.float64(0.698783642167052)), (304, np.float64(0.6986309020340711)), (1429, np.float64(0.698620670314504)), (979, np.float64(0.6983593289299969)), (2545, np.float64(0.6982692694900493)), (1596, np.float64(0.6980733257216196)), (5, np.float64(0.698065420169283)), (704, np.float64(0.6979208448787219)), (533, np.float64(0.6977919058761964)), (2988, np.float64(0.6974925506144697)), (962, np.float64(0.6973525075330028)), (2354, np.float64(0.6971099862500372)), (1327, np.float64(0.6969071235401351)), (2327, np.float64(0.6965402262845191)), (2984, np.float64(0.6965048705819713)), (629, np.float64(0.6962431697533519)), (1813, np.float64(0.6961239724283347)), (343, np.float64(0.6950123153712511)), (3454, np.float64(0.6948279195544308)), (2334, np.float64(0.6947324633676951)), (2541, np.float64(0.6947266525312478)), (1083, np.float64(0.6946949572951331)), (2578, np.float64(0.6941380384616092)), (507, np.float64(0.6938334459988618)), (669, np.float64(0.6937671702418786)), (569, np.float64(0.6937191993115848)), (770, np.float64(0.6

In [ ]:
print("movies suggested for you : \i")

i=1

for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=a[a.index==index]['title'].values[0]
  if(i<30):
    print(i, '.',title_from_index)
    i=i=1

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
/tmp/ipython-input-2008502279.py:1: SyntaxWarning: invalid escape sequence '\i'
  print("movies suggested for you : \i")

movies suggested for you : \i
1 . Spider-Man
1 . Jurassic World
1 . The Core
1 . The Day After Tomorrow
1 . Spider-Man 2
1 . War of the Worlds
1 . The Dark Knight Rises
1 . Contact
1 . Master and Commander: The Far Side of the World
1 . Cursed
1 . Catwoman
1 . The Wolf of Wall Street
1 . Bad Boys II
1 . Hulk
1 . Minority Report
1 . Blade: Trinity
1 . The League of Extraordinary Gentlemen
1 . Men in Black II
1 . Alexander
1 . Terminator 3: Rise of the Machines
1 . Freddy vs. Jason
1 . Tears of the Sun
1 . 15 Minutes
1 . Big Fish
1 . xXx
1 . Kill Bill: Vol. 1
1 . Blade II
1 . A.I. Artificial Intelligence
1 . The Aviator
1 . The Bourne Supremacy
1 . Harry Potter and the Prisoner of Azkaban
1 . The Alamo
1 . The Chronicles of Riddick
1 . Harry Potter and the Chamber of Secrets
1 . Ant-Man
1 . Collateral
1 . End of Days
1 . The Polar Express
1 . I, Robot
1 . Blade
1 . Collateral Damage
1 . Batman Begins
1 . Black Hawk Down
1 . The Fast and the Furious
1 . Harry Potter and the Philosopher's Stone
1 . Deep Blue Sea
1 . Austin Powers in Goldmember
1 . The Patriot
1 . Mission: Impossible II
1 . The Bourne Identity
1 . xXx: State of the Union
1 . The Bourne Ultimatum
1 . Dawn of the Planet of the Apes
1 . Pirates of the Caribbean: The Curse of the Black Pearl
1 . We Were Soldiers
1 . The Curious Case of Benjamin Button
1 . Scooby-Doo 2: Monsters Unleashed
1 . Exodus: Gods and Kings
1 . Ocean's Eleven
1 . Around the World in 80 Days
1 . Flight of the Phoenix
1 . Scary Movie 3
1 . National Treasure
1 . Man on Fire
1 . The Girl with the Dragon Tattoo
1 . The Fifth Element
1 . Men in Black
1 . Hidalgo
1 . The Haunting
1 . Elektra
1 . Charlie and the Chocolate Factory
1 . The Italian Job
1 . Captain America: The First Avenger
1 . What Lies Beneath
1 . The Village
1 . Dawn of the Dead
1 . Kill Bill: Vol. 2
1 . AVP: Alien vs. Predator
1 . Spectre
1 . Reign of Fire
1 . The Hunger Games: Mockingjay - Part 1
1 . Scooby-Doo
1 . Deep Impact
1 . Troy
1 . Dude, Where’s My Car?
1 . Fantastic Four
1 . The Butterfly Effect
1 . Thir13en Ghosts
1 . The Ring Two
1 . Fast Five
1 . The Bone Collector
1 . Casino Royale
1 . Road to Perdition
1 . Timeline
1 . Bruce Almighty
1 . Batman & Robin
1 . Captain America: Civil War
1 . Terminator Genisys
1 . Darkness Falls
1 . Mindhunters
1 . Interstellar
1 . Fight Club
1 . Apollo 13
1 . American Beauty
1 . Jurassic Park III
1 . Herbie Fully Loaded
1 . Knight and Day
1 . Jay and Silent Bob Strike Back
1 . The Interpreter
1 . Ocean's Twelve
1 . Kingdom of Heaven
1 . Dante's Peak
1 . Eagle Eye
1 . 50 First Dates
1 . Avatar
1 . The X Files: I Want to Believe
1 . Angels & Demons
1 . Space Jam
1 . The Abyss
1 . Cloud Atlas
1 . Entrapment
1 . 2 Fast 2 Furious
1 . Jurassic Park
1 . Live Free or Die Hard
1 . Don't Say a Word
1 . Clash of the Titans
1 . The Amazing Spider-Man 2
1 . American Wedding
1 . The Avengers
1 . Saving Private Ryan
1 . Ladder 49
1 . Pearl Harbor
1 . The Sum of All Fears
1 . Last Action Hero
1 . S.W.A.T.
1 . Lost in Space
1 . The Lost World: Jurassic Park
1 . The Punisher
1 . Hellboy
1 . Speed 2: Cruise Control
1 . Air Force One
1 . Sahara
1 . Torque
1 . Out of Time
1 . Spanglish
1 . Warcraft
1 . Gothika
1 . Assault on Precinct 13
1 . Edge of Tomorrow
1 . Scary Movie 2
1 . The Hobbit: The Battle of the Five Armies
1 . Ghost Ship
1 . Dracula Untold
1 . Ender's Game
1 . Bandits
1 . DodgeBall: A True Underdog Story
1 . John Q
1 . Starsky & Hutch
1 . American Pie 2
1 . EuroTrip
1 . John Carter
1 . The Revenant
1 . Armageddon
1 . The Hunger Games: Mockingjay - Part 2
1 . The Artist
1 . Battleship
1 . The Musketeer
1 . House on Haunted Hill
1 . The Bourne Legacy
1 . Paycheck
1 . The Skeleton Key
1 . The Girl Next Door
1 . Wrong Turn
1 . The Brothers Grimm
1 . Meet the Fockers
1 . The Expendables
1 . Mercury Rising
1 . House of Wax
1 . The Twilight Saga: Breaking Dawn - Part 2
1 . Mission: Impossible
1 . Batman v Superman: Dawn of Justice
1 . Eight Legged Freaks
1 . Erin Brockovich
1 . Jeepers Creepers 2
1 . Elysium
1 . Forrest Gump
1 . The Social Network
1 . Star Trek Beyond
1 . The Hobbit: The Desolation of Smaug
1 . Catch Me If You Can
1 . Bowfinger
1 . Red Planet
1 . Jason Bourne
1 . L.A. Confidential
1 . The Passion of the Christ
1 . What Women Want
1 . The Amazing Spider-Man
1 . Fear and Loathing in Las Vegas
1 . Star Trek Into Darkness
1 . Twister
1 . The Da Vinci Code
1 . Resident Evil: Apocalypse
1 . Lethal Weapon 4
1 . The Manchurian Candidate
1 . Me, Myself & Irene
1 . Bridget Jones's Diary
1 . Mission: Impossible - Rogue Nation
1 . The Expendables 2
1 . Signs
1 . Everyone Says I Love You
1 . Rise of the Planet of the Apes
1 . Guardians of the Galaxy
1 . V for Vendetta
1 . The Animal
1 . The Spiderwick Chronicles
1 . Sky Captain and the World of Tomorrow
1 . Independence Day: Resurgence
1 . Children of Men
1 . Public Enemies
1 . Ghostbusters
1 . Black Swan
1 . The Jackal
1 . Without a Paddle
1 . Anaconda
1 . A Good Day to Die Hard
1 . Alien: Resurrection
1 . The Siege
1 . Point Break
1 . The Sixth Sense
1 . Battle: Los Angeles
1 . Suicide Squad
1 . Cloverfield
1 . Escape Plan
1 . Swimfan
1 . Divergent
1 . Bringing Out the Dead
1 . X-Men: Days of Future Past
1 . 3:10 to Yuma
1 . The Relic
1 . Spotlight
1 . Pitch Black
1 . Fury
1 . 8 Mile
1 . Underworld
1 . Dreamcatcher
1 . Final Destination 2
1 . Alice Through the Looking Glass
1 . The Finest Hours
1 . Gamer
1 . Monsters, Inc.
1 . 2012
1 . Frequency
1 . Zoolander
1 . The Man from U.N.C.L.E.
1 . The Book of Eli
1 . The Whole Ten Yards
1 . American History X
1 . Captain Phillips
1 . Bridget Jones: The Edge of Reason
1 . Final Destination 3
1 . Hard Rain
1 . Se7en
1 . The Peacemaker
1 . X-Men: Apocalypse
1 . The Big Lebowski
1 . The Great Raid
1 . Django Unchained
1 . A Knight's Tale
1 . Unbroken
1 . Gone Girl
1 . The Martian
1 . White Noise
1 . Thank You for Smoking
1 . Furious 7
1 . Joy
1 . Punisher: War Zone
1 . American Pie
1 . They
1 . Blood Diamond
1 . The King's Speech
1 . The Wolverine
1 . Sin City
1 . Daylight
1 . Meet the Parents
1 . Prometheus
1 . The Maze Runner
1 . Night at the Museum: Secret of the Tomb
1 . Taken 3
1 . Gladiator
1 . Maze Runner: The Scorch Trials
1 . The Water Diviner
1 . Liar Liar
1 . There's Something About Mary
1 . Bullet to the Head
1 . Dream House
1 . San Andreas
1 . Deep Rising
1 . Along Came Polly
1 . In the Heart of the Sea
1 . Resident Evil
1 . I Still Know What You Did Last Summer
1 . The Shawshank Redemption
1 . Crank: High Voltage
1 . Jupiter Ascending
1 . House of 1000 Corpses
1 . Doomsday
1 . Secret Window
1 . Cold Mountain
1 . The Silence of the Lambs
1 . Old Dogs
1 . Scream
1 . The Whole Nine Yards
1 . Body of Lies
1 . Jumper
1 . Deadpool
1 . Bridge of Spies
1 . I, Frankenstein
1 . Dead Man Walking
1 . Jeepers Creepers
1 . Flyboys
1 . The Order
1 . The Incredibles
1 . 300: Rise of an Empire
1 . 13 Hours: The Secret Soldiers of Benghazi
1 . Colombiana
1 . Transformers: Age of Extinction
1 . Gangster Squad
1 . Die Hard
1 . The Big Short
1 . Everest
1 . The Dark Knight
1 . Snake Eyes
1 . Black Mass
1 . The Hateful Eight
1 . The Cabin in the Woods
1 . The Crazies
1 . Tomorrowland
1 . Into the Storm
1 . Marley & Me
1 . Edge of Darkness
1 . Wicker Park
1 . The One
1 . Land of the Dead
1 . Green Zone
1 . Allegiant
1 . Million Dollar Baby
1 . The Fountain
1 . Journey 2: The Mysterious Island
1 . Drive
1 . Dreamgirls
1 . London Has Fallen
1 . Maid in Manhattan
1 . I Know What You Did Last Summer
1 . Finding Nemo
1 . Elizabeth: The Golden Age
1 . Eraser
1 . Diary of a Wimpy Kid
1 . The Day the Earth Stood Still
1 . Drag Me to Hell
1 . Nightcrawler
1 . Payback
1 . 8MM
1 . Aloha
1 . The Departed
1 . Equilibrium
1 . Club Dread
1 . Predator 2
1 . No Strings Attached
1 . The Butler
1 . Final Destination
1 . Four Rooms
1 . Dredd
1 . Shrek
1 . The Theory of Everything
1 . Die Hard 2
1 . Insurgent
1 . Deliver Us from Evil
1 . Crank
1 . Noah
1 . The Conspirator
1 . Dumb and Dumber
1 . Anacondas: The Hunt for the Blood Orchid
1 . The Possession
1 . A Most Violent Year
1 . Dragonfly
1 . 12 Years a Slave
1 . The Bucket List
1 . American Sniper
1 . Don't Be Afraid of the Dark
1 . Survivor
1 . I Love You, Man
1 . The Chronicles of Narnia: Prince Caspian
1 . District 9
1 . Victor Frankenstein
1 . The Equalizer
1 . Avengers: Age of Ultron
1 . Mad Max: Fury Road
1 . Shark Tale
1 . Braveheart
1 . Carrie
1 . 300
1 . 47 Ronin
1 . JFK
1 . Nebraska
1 . The Last Witch Hunter
1 . Enemy at the Gates
1 . Hugo
1 . Maggie
1 . Doom
1 . Hot Tub Time Machine 2
1 . Exit Wounds
1 . Brooklyn
1 . Transcendence
1 . The Lovers
1 . Australia
1 . Apocalypto
1 . The Cell
1 . Movie 43
1 . Now You See Me 2
1 . Brooklyn's Finest
1 . Panic Room
1 . Juno
1 . The Black Dahlia
1 . Red Tails
1 . The 5th Wave
1 . Beyond the Lights
1 . Gods and Generals
1 . The Expendables 3
1 . Dances with Wolves
1 . Gods of Egypt
1 . Freedom Writers
1 . The Dukes of Hazzard
1 . Faster
1 . Ultraviolet
1 . Our Kind of Traitor
1 . Walk the Line
1 . Meet Joe Black
1 . Cinderella
1 . Flipped
1 . The First Wives Club
1 . 127 Hours
1 . Let's Be Cops
1 . Shrek 2
1 . Invaders from Mars
1 . Seabiscuit
1 . Sinister 2
1 . Up
1 . Stardust
1 . Beowulf
1 . Concussion
1 . Death Sentence
1 . Saw
1 . After Earth
1 . The Country Bears
1 . Clockstoppers
1 . Brothers
1 . Dr. Dolittle 2
1 . Just Like Heaven
1 . The Terminal
1 . The Exorcism of Emily Rose
1 . The Cave
1 . The Adjustment Bureau
1 . Flight
1 . The Book Thief
1 . Into the Woods
1 . Drive Angry
1 . The Matrix
1 . Terminator 2: Judgment Day
1 . Alexander and the Terrible, Horrible, No Good, Very Bad Day
1 . Triple 9
1 . How High
1 . Ronin
1 . Ella Enchanted
1 . Little Miss Sunshine
1 . Chronicle
1 . Atlantis: The Lost Empire
1 . Lucy
1 . Apollo 18
1 . The Constant Gardener
1 . Wild
1 . Sphere
1 . Predators
1 . The Purge: Anarchy
1 . The 6th Day
1 . Whiplash
1 . Hercules
1 . Broken City
1 . Free State of Jones
1 . End of Watch
1 . Sicario
1 . Spider-Man 3
1 . Antz
1 . Monster House
1 . The Grudge
1 . Raising Helen
1 . Steve Jobs
1 . Creed
1 . Predator
1 . Madea's Family Reunion
1 . Need for Speed
1 . Gran Torino
1 . Toy Story 2
1 . The Usual Suspects
1 . Birdman
1 . The Faculty
1 . Babylon A.D.
1 . The Marine
1 . Independence Day
1 . Sin City: A Dame to Kill For
1 . The SpongeBob Movie: Sponge Out of Water
1 . Event Horizon
1 . Midnight in Paris
1 . The Darkest Hour
1 . Ghost
1 . The Fault in Our Stars
1 . American Gangster
1 . The Ides of March
1 . Hellraiser
1 . GoodFellas
1 . Silver Linings Playbook
1 . Harry Brown
1 . Think Like a Man
1 . Waterworld
1 . From Hell
1 . Assassins
1 . Aliens vs Predator: Requiem
1 . Amélie
1 . Toy Story
1 . Snatch
1 . Enough
1 . Case 39
1 . The Prestige
1 . Four Brothers
1 . Ted 2
1 . 27 Dresses
1 . A Walk Among the Tombstones
1 . Frankenweenie
1 . Reservoir Dogs
1 . Post Grad
1 . Ghost Rider
1 . Arbitrage
1 . Role Models
1 . Transformers: Revenge of the Fallen
1 . Basic
1 . Kung Pow: Enter the Fist
1 . Child 44
1 . In the Valley of Elah
1 . Return to Oz
1 . The Fast and the Furious: Tokyo Drift
1 . Supernova
1 . Centurion
1 . Mortdecai
1 . Under the Skin
1 . The Fighter
1 . A Beautiful Mind
1 . Splice
1 . Central Intelligence
1 . Willard
1 . Krampus
1 . Dark City
1 . The Talented Mr. Ripley
1 . Patch Adams
1 . The Life of David Gale
1 . Ex Machina
1 . From Paris with Love
1 . Feast
1 . The Forest
1 . The Conjuring 2
1 . Looney Tunes: Back in Action
1 . 10 Cloverfield Lane
1 . Argo
1 . Good Will Hunting
1 . United 93
1 . Midnight Special
1 . The Sweetest Thing
1 . From Dusk Till Dawn
1 . Abduction
1 . The Last of the Mohicans
1 . Ouija
1 . Terminator Salvation
1 . No Good Deed
1 . K-PAX
1 . 17 Again
1 . Unbreakable
1 . Ed Wood
1 . Daybreakers
1 . The Veil
1 . Conan the Barbarian
1 . The Island
1 . The Hunger Games
1 . Flags of Our Fathers
1 . American Psycho
1 . Spring Breakers
1 . The Homesman
1 . Chernobyl Diaries
1 . Winnie the Pooh
1 . Wild Card
1 . Bless the Child
1 . Tombstone
1 . Bait
1 . Robots
1 . The Bodyguard
1 . Blackhat
1 . The Terminator
1 . Blood Ties
1 . First Blood
1 . Florence Foster Jenkins
1 . Happy Feet
1 . Rain Man
1 . The Grey
1 . Death Race
1 . Earth to Echo
1 . The Mist
1 . Superman II
1 . Moneyball
1 . Deadfall
1 . The Adventures of Sharkboy and Lavagirl
1 . The Purge: Election Year
1 . Run All Night
1 . FearDotCom
1 . Left Behind
1 . Slumdog Millionaire
1 . Race
1 . The Duchess
1 . eXistenZ
1 . Aladdin
1 . Black Book
1 . Indiana Jones and the Last Crusade
1 . Eastern Promises
1 . The Good German
1 . The Hunted
1 . The Help
1 . Man of Steel
1 . Cinderella Man
1 . 50/50
1 . Mr. Holland's Opus
1 . WALL·E
1 . The Master
1 . Osmosis Jones
1 . Paul
1 . Pete's Dragon
1 . A Few Good Men
1 . The Empire Strikes Back
1 . Incendies
1 . Annie
1 . Insidious: Chapter 3
1 . The Tale of Despereaux
1 . Due Date
1 . Green Room
1 . Raiders of the Lost Ark
1 . The Shallows
1 . 30 Days of Night
1 . War Horse
1 . Ice Age
1 . The Bank Job
1 . Showdown in Little Tokyo
1 . Behind Enemy Lines
1 . The Signal
1 . Small Soldiers
1 . Ramona and Beezus
1 . The Collection
1 . Snow White and the Seven Dwarfs
1 . Titanic
1 . Gravity
1 . Madagascar
1 . Die Hard: With a Vengeance
1 . Contagion
1 . The Conjuring
1 . Secretariat
1 . The Doors
1 . The Boy
1 . Hachi: A Dog's Tale
1 . The Others
1 . 13 Going on 30
1 . Into the Wild
1 . An American Haunting
1 . Horrible Bosses
1 . The Astronaut's Wife
1 . Slow West
1 . Snow White and the Huntsman
1 . Letters from Iwo Jima
1 . Percy Jackson & the Olympians: The Lightning Thief
1 . The Neon Demon
1 . Bats
1 . GoldenEye
1 . Agent Cody Banks
1 . Bachelorette
1 . Evil Dead
1 . The Bad Lieutenant: Port of Call - New Orleans
1 . The Devil's Double
1 . Elf
1 . I Am Wrath
1 . X-Men: The Last Stand
1 . Soldier
1 . A Dangerous Method
1 . 28 Weeks Later
1 . Seventh Son
1 . The Princess and the Frog
1 . The Hobbit: An Unexpected Journey
1 . Conan the Destroyer
1 . The American
1 . Ted
1 . Bolt
1 . Boogeyman
1 . Glory
1 . Snow White: A Tale of Terror
1 . Corpse Bride
1 . Labor Day
1 . Sabotage
1 . Trainspotting
1 . Face/Off
1 . The Hunger Games: Catching Fire
1 . X-Men: First Class
1 . Demonic
1 . Galaxy Quest
1 . The Godfather: Part II
1 . Just Go with It
1 . Closer
1 . Elizabeth
1 . Green Lantern
1 . The Notebook
1 . Maria Full of Grace
1 . Les Misérables
1 . The Green Mile
1 . Grabbers
1 . Money Train
1 . Law Abiding Citizen
1 . The Wolfman
1 . Tangled
1 . Alien³
1 . Agora
1 . Cabin Fever
1 . Mr. Turner
1 . The Debt
1 . Automata
1 . Before I Go to Sleep
1 . The Glass House
1 . Taxi Driver
1 . Infamous
1 . The Green Inferno
1 . The Prince
1 . The Boy in the Striped Pyjamas
1 . Fortress
1 . Patton
1 . Real Steel
1 . Me Before You
1 . Arn: The Knight Templar
1 . Blood and Wine
1 . 9
1 . Dancer in the Dark
1 . As Above, So Below
1 . 12 Rounds
1 . The Lazarus Effect
1 . Gone with the Wind
1 . By the Sea
1 . Spy Kids 2: The Island of Lost Dreams
1 . The Sea Inside
1 . Lucky You
1 . Red Riding Hood
1 . Lawrence of Arabia
1 . Gattaca
1 . The Walk
1 . Transformers
1 . Syriana
1 . Spy Kids
1 . The Men Who Stare at Goats
1 . Awake
1 . Submarine
1 . Coriolanus
1 . Downfall
1 . Raging Bull
1 . Oculus
1 . Joyful Noise
1 . American Heist
1 . Devil
1 . The Blind Side
1 . Sky High
1 . Take Me Home Tonight
1 . Meet Dave
1 . 3 Days to Kill
1 . Nancy Drew
1 . The Legend of Hercules
1 . Cube
1 . Wolf
1 . The Cottage
1 . The Change-Up
1 . Captive
1 . The Simpsons Movie
1 . The Sting
1 . Hostel
1 . The Thing
1 . The Infiltrator
1 . Ratatouille
1 . The Remains of the Day
1 . Final Destination 5
1 . Sucker Punch
1 . The Insider
1 . Species
1 . Prince of Persia: The Sands of Time
1 . Insomnia
1 . The Last House on the Left
1 . The Wrestler
1 . 21 Jump Street
1 . Annie Hall
1 . Legend
1 . The Calling
1 . Magnolia
1 . Self/less
1 . Starship Troopers
1 . Joyeux Noël
1 . Tammy
1 . The Boxtrolls
1 . The Secret Life of Pets
1 . Marvin's Room
1 . The Three Burials of Melquiades Estrada
1 . The Sweeney
1 . Get on Up
1 . Zodiac
1 . Pompeii
1 . Revolutionary Road
1 . Identity Thief
1 . Back to the Future
1 . Mean Girls
1 . Groundhog Day
1 . One Flew Over the Cuckoo's Nest
1 . Captain America: The Winter Soldier
1 . Bad Teacher
1 . Young Adult
1 . Ocean's Thirteen
1 . Away We Go
1 . Thor: The Dark World
1 . Lara Croft: Tomb Raider
1 . Pulp Fiction
1 . Dying of the Light
1 . The DUFF
1 . The Imitation Game
1 . Dune
1 . Unforgiven
1 . Chappie
1 . Flame & Citron
1 . Nerve
1 . Home Alone
1 . The Lego Movie
1 . The Boy Next Door
1 . The Iron Giant
1 . The Town
1 . Cellular
1 . 42
1 . Annabelle
1 . The Adventures of Tintin
1 . True Romance
1 . The Rainmaker
1 . Top Gun
1 . Easy A
1 . The White Countess
1 . This Means War
1 . Appaloosa
1 . Glengarry Glen Ross
1 . The Deer Hunter
1 . King Kong
1 . The Lost Boys
1 . Commando
1 . Yes Man
1 . Arlington Road
1 . 1408
1 . Jack the Giant Slayer
1 . We're the Millers
1 . Step Up 2: The Streets
1 . Apocalypse Now
1 . Animal House
1 . The Witch
1 . Girl, Interrupted
1 . Titan A.E.
1 . The Devil's Rejects
1 . Heartbreakers
1 . 54
1 . Looper
1 . Mission to Mars
1 . Snowpiercer
1 . The Godfather
1 . Act of Valor
1 . A Most Wanted Man
1 . Futuro Beach
1 . The Grand Budapest Hotel
1 . The Elephant Man
1 . Warrior
1 . Aliens
1 . Any Given Sunday
1 . The Illusionist
1 . After.Life
1 . No Escape
1 . Spider
1 . Inside Out
1 . Sherlock Holmes: A Game of Shadows
1 . The Gift
1 . Charlie Bartlett
1 . Ever After: A Cinderella Story
1 . Instinct
1 . Charlie's Angels
1 . Once Upon a Time in Mexico
1 . Bambi
1 . Fantasia 2000
1 . Forsaken
1 . Frost/Nixon
1 . Intolerable Cruelty
1 . Grace of Monaco
1 . Big Mommas: Like Father, Like Son
1 . Cars 2
1 . The Twilight Saga: Eclipse
1 . Paris, je t'aime
1 . Lady in the Water
1 . Young Frankenstein
1 . All Is Lost
1 . Neighbors
1 . Hoffa
1 . The Pianist
1 . American Dreamz
1 . Scarface
1 . Coraline
1 . Prisoners
1 . Inglourious Basterds
1 . How to Train Your Dragon
1 . Vera Drake
1 . Final Fantasy: The Spirits Within
1 . Vacation
1 . Firefox
1 . Things We Lost in the Fire
1 . The Queen
1 . The Sitter
1 . Big Hero 6
1 . Lone Survivor
1 . The Descent
1 . Home on the Range
1 . Crazy, Stupid, Love.
1 . Big Daddy
1 . Toy Story 3
1 . The Transporter Refueled
1 . Prom Night
1 . One Missed Call
1 . I Am Sam
1 . The Last King of Scotland
1 . Match Point
1 . Curious George
1 . Desert Dancer
1 . Ghost Rider: Spirit of Vengeance
1 . She's Out of My League
1 . Schindler's List
1 . Triangle
1 . Kick-Ass
1 . Freaky Deaky
1 . Fifty Dead Men Walking
1 . A Monster in Paris
1 . Pirates of the Caribbean: On Stranger Tides
1 . The Timber
1 . The Rage: Carrie 2
1 . Beneath Hill 60
1 . Devil's Due
1 . Dogma
1 . Focus
1 . Paparazzi
1 . Mongol: The Rise of Genghis Khan
1 . Driving Miss Daisy
1 . The Squid and the Whale
1 . Laws of Attraction
1 . Daddy Day Care
1 . Brick Mansions
1 . GirlHouse
1 . Skin Trade
1 . Blade Runner
1 . Donnie Darko
1 . Pinocchio
1 . The Flowers of War
1 . Con Air
1 . The Lord of the Rings: The Two Towers
1 . A History of Violence
1 . Invasion U.S.A.
1 . Pirates of the Caribbean: At World's End
1 . Chicken Little
1 . Oz: The Great and Powerful
1 . Joe
1 . Lost in Translation
1 . Underworld: Awakening
1 . Thirteen Days
1 . Changeling
1 . The Devil Inside
1 . September Dawn
1 . Diner
1 . The Last Days on Mars
1 . The Ultimate Gift
1 . Some Like It Hot
1 . Joe Somebody
1 . Regression
1 . Bridesmaids
1 . Platoon
1 . Hall Pass
1 . Sex Tape
1 . Escape from Alcatraz
1 . Sex Drive
1 . Pan's Labyrinth
1 . One Hour Photo
1 . The Legend of Hell's Gate: An American Conspiracy
1 . Chicken Run
1 . Crash
1 . Walking Tall
1 . Fun with Dick and Jane
1 . Cape Fear
1 . Six Days Seven Nights
1 . Grindhouse
1 . Hannah Montana: The Movie
1 . The Devil's Tomb
1 . Blood and Chocolate
1 . The Judge
1 . Ironclad
1 . Anastasia
1 . Chocolat
1 . The Lady from Shanghai
1 . 28 Days Later
1 . Lake Placid
1 . Hotel Rwanda
1 . Criminal Activities
1 . The Gunman
1 . Project Almanac
1 . Little Children
1 . You Don't Mess with the Zohan
1 . Darkness
1 . Fifty Shades of Grey